version: '3'
services:
  fake-simple-json-datasource: # Fake source to test the plugin
    image: hadesarchitect/fake-simple-json-datasource
    ports:
      - "3333:3333"
  grafana: # Grafana
    image: grafana/grafana:8.1.2
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
    volumes:
      - ./dist:/var/lib/grafana/plugins/simple-json-pkg
